config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'homes#top'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'account', to: 'dashboards#account'
  patch 'account', to: 'dashboards#update'

  get 'questions' => 'questions#index'
  get 'answers/search', to: 'answers#search'
  get 'answers' => 'answers#index'

  #タグ
  get 'tags/:tag_name', to: 'homes#tagged_questions', as: :tagged_questions

  # 退会確認画面
  get '/unsubscribe', to: 'dashboards#unsubscribe', as: 'unsubscribe'

  # 論理削除用のルーティング
  patch '/withdrawal', to: 'dashboards#withdrawal', as: 'withdrawal'

  resources :questions, shallow: true do
    resources :answers, shallow: true do
      resources :reactions
    end
  end

  resources :admin_articles, only: [:index, :show], path: 'articles'
end

app/models/question.rb
# frozen_string_literal: true

# 質問はユーザーに属し、複数の回答を持ち、複数のタグを持つ
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags
  has_one_attached :image

  validates :title, presence: true
  validates :body, presence: true
  validates :views_count, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    ['best_answer_id', 'body', 'created_at', 'id', 'title', 'updated_at', 'user_id', 'views_count', 'image_attached?']
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[answers question_tags tags user]
  end

  delegate :attached?, to: :image, prefix: true

  scope :with_image, -> { joins(:image_attachment) }
  scope :without_image, -> { left_outer_joins(:image_attachment).where(active_storage_attachments: { id: nil }) }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

# 質問の作成、読み取り、更新、削除、検索
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]
  before_action :set_best_answer, only: %i[update]
  before_action :ensure_correct_user, only: %i[edit update destroy]

  # 質問一覧表示
  def index
    @tags = Tag.all
    if params[:tag]
      @tag = Tag.find_by(name: params[:tag])
      @questions = @tag ? @tag.questions : Question.none
    else
      @questions = current_user.questions.all
    end
  end

  # 質問詳細表示
  def show; end

  # 新規質問作成
  def new
    @question = Question.new
    @tags = Tag.all
  end

  # 質問編集
  def edit
    @tags = Tag.all
  end

  # 質問投稿
  def create
    @question = current_user.questions.build(question_params)
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: t('.success') }
        format.json { render :show, status: :created, location: @question }
      else
        flash[:error] = t('.error')
        @tags = Tag.all
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: t('.success') }
        format.json { render :show, status: :ok, location: @question }
      else
        # flash[:error] = t('.error')
        flash[:error] = @question.errors.full_messages.join(', ')
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # 質問削除
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: t('questions.delete.success') }
      format.json { head :no_content }
    end
  end

  private

  # 共通の設定や制約を共有するためのコールバック
  def set_question
    @question = Question.find(params[:id])
    @tags = Tag.all
  end

  # 信頼できるパラメータのみ許可する
  def question_params
    params.require(:question).permit(:title, :body, :image, :best_answer_id, { tag_ids: [] })
  end

  # ベストアンサーのセット
  def set_best_answer
    return if @question.best_answer_id.blank?

    redirect_to @question, alert: t('questions.update.best_answer_chosen')
  end

  # 正しいユーザーか確認する
  def ensure_correct_user
    redirect_to(questions_path) unless @question.user_id == current_user.id
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: @question) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <div class="field mb-3 w-100 row ml-0 mr-0">
      <%= form.label :title, 'タイトル' %>
      <%= form.text_field :title, class:"col-8 form-control" %>
    </div>

    <div class="field mb-3 w-100 row ml-0 mr-0">
      <%= form.label :body, '内容' %>
      <%= form.text_area :body, class:"col-8 form-control" %>
    </div>

    <div class="field mb-3 w-100 row ml-0 mr-0">
      <%= form.label :image, '画像' %>
      <%= form.file_field :image, class:"col-8 form-control" %>
    </div>

    <div class="form-group my-3">
      <label class="mb-2">タグ</label>
      <% @tags.each do |t| %>
        <div class="form-check">
          <%= check_box_tag "question[tag_ids][]", t.id, @question.tags.include?(t), class: "form-check-input" %>
          <%= label_tag "question[tag_ids][]", t.name, class: "form-check-label" %>
        </div>
      <% end %>
    </div>


    <div class="actions">
      <%= form.submit '投稿', class: 'btn btn-success'  %>
    </div>
<% end %>

app/views/questions/edit.html.erb
<div class="container">
  <div class="bg-light p-5 rounded my-4">
    <h2 class="col-12 ms-2">質問の編集</h2>
  </div>
  <%= render 'form', question: @question %>

  <div class="my-4">
    <%= link_to '現在の質問に戻る', question_path(@question), class: "link-success me-3" %>
    <%= link_to '質問投稿一覧', questions_path, class: "link-success me-3" %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="container justify-content-center p-3">
  <div class="bg-light p-5 rounded my-4">
    <h2 class="col-12 ms-2">質問投稿一覧</h2>
  </div>

  <div class="row text-center py-3 px-5">
    <% if @questions.empty? %>
      <div class="p-5">
        <h5>まだ質問がありません。質問してみましょう！</h5>
        <%= link_to '質問する！', new_question_path, class: 'btn btn-success' %>
      </div>
    <% else %>
      <% @questions.each do |question| %>
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card h-100">
            <div class="card-img-container">
              <% if question.image.attached? %>
                <%= image_tag question.image, class: "card-img-top" %>
              <% else %>
                <%= image_tag "question.png", class: "card-img-top" %>
              <% end %>
            </div>
            <div class="card-body">
              <h4 class="card-title question-title"><%= question.title %></h4>
              <p class="card-text  question-body"><%= question.body %></p>
            </div>
            <div class="card-footer">
              <%= link_to '詳細', question %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="my-4">
    <%= link_to "トップページ", root_path, class: "link-success me-3" %>
    <%= link_to "回答募集一覧", answers_path, class: "link-success me-3" %>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container justify-content-center p-5">
  <div class="bg-light p-5 rounded my-4">
    <h2 class="col-12 ms-2">質問投稿</h2>
  </div>
  <%= render 'form', question: @question %>

  <div class="my-4">
    <%= link_to '前のページに戻る', request.referer || root_path, class: "link-success me-3" %>
    <%= link_to "質問投稿一覧", questions_path, class: "link-success me-3" %>
    <%= link_to "回答募集一覧", answers_path, class: "link-success me-3" %>
  </div>
</div>

app/views/questions/search.html.erb
<div class="question container justify-content-center p-5">
  <div class="row">
    <% if @question.present? %>
      <h3 class="col-12 search-number">検索結果 <%= @cnt %>件です</h3>
        <% @question.each do |question| %>
          <div class="col-12">
            <div class="question-search-frame">
              <div class="card">
                <div class="question-search-profile card-header">
                <% if question.user&.image.present? %>
                  <%= image_tag url_for(question.user.image), class: "rounded-circle", size: "45x45" %>
                <% else %>
                  <%= image_tag "rabbit_logo.png", class: "rounded-circle", size: "45x45" %>
                <% end %>
                  <%= question.user.name %>
                </div>
                <div class="card-body">
                  <%= link_to question_path(question.id),class:"question-link link-success" do %>
                    <div class="search-title card-title"><%= question.title %></div>
                  <% end %>
                  <div class="search-body card-text"><%= question.body %></div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
    <% else %>
      <div>
        <h3>検索結果はありませんでした</h3>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container">

  <div class="bg-light p-5 rounded my-4">
    <h2 class="col-12 ms-2">投稿した質問</h2>
  </div>
  <div class="card-body my-5">
    <div class="d-flex justify-content-between">

      <div>
        <div class="my-3">
          <% if @question.user.image.attached? %>
            <%= image_tag @question.user.image, class: "rounded-circle", size: "60x60" %>
          <%else%>
            <%= image_tag "rabbit_logo.png", class: "rounded-circle", size: "60x60" %>
          <%end%>
          <span class="<%= "user_color" if current_user && current_user.id == @question.user_id %>">
            <%= @question.user.name %>
          </span><br>
        </div>
        タイトル：<%= @question.title %><br>
        内容：<%= @question.body %><br>
        <div class="my-3">
          <% @question.tags.each do |tag| %>
            <%= link_to tagged_questions_path(tag_name: tag.name), class: "btn btn-info" do %>
              <%= tag.name %>
            <% end %>
          <% end %>
        </div>
        <div>
          <% if @question.image.attached? %>
            <%= image_tag @question.image, class: "my-5 question-img" %>
          <% end %>
        </div>
      </div>

      <div>
        <% if current_user && current_user.id == @question.user_id %>
          <div class="d-flex">
            <%= link_to_unless @question.best_answer_id, '編集', edit_question_path(@question), class: 'btn bg-light me-1 px-3 btn-responsive' %>
            <button type="button" class="btn btn-danger px-3 btn-responsive" data-bs-toggle="modal" data-bs-target="#deleteModal">削除</button>
          </div>

          <!-- Modal -->
          <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteModalLabel">削除確認</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  質問を削除してもよろしいですか？この操作は元に戻せません。
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                  <%= link_to '削除', question_path(@question), method: :delete, class: 'btn btn-danger' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <% @question.answers.each do |answer| %>
      <div class="col-lg-11 col-md-11">
        <div class="card h-100">
          <div class="card-body  <%= "best-answer" if @question.best_answer_id == answer.id %>">

            <div class="my-3">
              <% if answer.user.image.attached? %>
                <%= image_tag answer.user.image, class: "rounded-circle", size: "60x60" %>
              <%else%>
                <%= image_tag "rabbit_logo.png", class: "rounded-circle", size: "60x60" %>
              <%end%>
              <span class="<%= "user_color" if current_user && current_user.id == answer.user_id %>">
                <%= answer.user.name %>
              </span><br>
            </div>
            <div><%= answer.body %></div>

            <% answer.reactions.each do |reaction| %>
              <div class="row">
                <div class="col-lg-12 col-md-12">
                  <div class="card h-100">
                    <div class="card-body">
                      <div><%= reaction.body %></div>


                      <% if current_user && current_user.id == reaction.user_id %>
                        <div style="text-align: right;">
                          <%= link_to "編集", edit_reaction_path(reaction), class: "btn btn-light" %>
                          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal-<%= reaction.id %>">
                            削除
                          </button>
                        </div>

                        <!-- Modal -->
                        <div class="modal fade" id="deleteModal-<%= reaction.id %>" tabindex="-1" aria-labelledby="deleteModalLabel-<%= reaction.id %>" aria-hidden="true">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel-<%= reaction.id %>">削除の確認</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
                              </div>
                              <div class="modal-body">
                                この返信を削除してよろしいですか？
                              </div>
                              <div class="modal-footer">
                                <%= link_to "削除", reaction_path(reaction), method: :delete, class: "btn btn-danger" %>
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                              </div>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <br>
            <% end %>
            <% if current_user && current_user.id == @question.user_id %>
              <p class="text-right"><%= link_to '返信する', new_answer_reaction_path(answer.id), class: 'link-success' %></p>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-lg-1 col-md-1 ba-parent mb-3">
        <div class="ba-child text-center">
          <% if current_user == @question.user %>
            <%= form_with(model: @question, local: true, id: 'bestAnswerForm') do |form| %>
              <%= form.hidden_field :best_answer_id, id: 'bestAnswerId', value: answer.id %>
              <div class="actions">
                <button type="button" class="btn rounded-pill bg-warning text-white" data-bs-toggle="modal" data-bs-target="#confirmModal" <%= 'disabled' if @question.best_answer_id.present? %>>Best</button>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

      <!-- Modal -->
      <div class="modal fade" id="confirmModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">確認</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%= answer.user.name %>さんの回答をベストアンサーにします。変更できませんが、よろしいですか？
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
              <button type="button" class="btn btn-primary" id="confirmButton">確定</button>
            </div>
          </div>
        </div>
      </div>

      <script>
      document.getElementById('confirmButton').addEventListener('click', function() {
        document.getElementById('bestAnswerForm').submit();
      });
      </script>
    <% end %>
  </div>

  <div class="my-4">
    <%= link_to '質問投稿一覧', questions_path, class: "link-success" %>
  </div>
</div>