config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'homes#top'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'account', to: 'dashboards#account'
  patch 'account', to: 'dashboards#update'

  get 'questions' => 'questions#index'
  get 'answers/search', to: 'answers#search'
  get 'answers' => 'answers#index'

  #タグ
  get 'tags/:tag_name', to: 'homes#tagged_questions', as: :tagged_questions

  # 退会確認画面
  get '/unsubscribe', to: 'dashboards#unsubscribe', as: 'unsubscribe'

  # 論理削除用のルーティング
  patch '/withdrawal', to: 'dashboards#withdrawal', as: 'withdrawal'

  resources :questions, shallow: true do
    resources :answers, shallow: true do
      resources :reactions
    end
  end

  resources :admin_articles, only: [:index, :show], path: 'articles'
end

app/controllers/reactions_controller.rb
# frozen_string_literal: true

# ユーザーの返信を処理するクラス
class ReactionsController < ApplicationController
  before_action :set_reaction, only: %i[show edit update destroy]
  before_action :find_answer, only: %i[new create]
  before_action :ensure_correct_user, only: %i[edit update destroy]

  # 全てのリアクションを表示する
  def index
    @reactions = Reaction.all
  end

  # 特定のリアクションを表示する
  def show; end

  # 新しいリアクションを作成するための画面
  def new
    @reaction = @answer.reactions.build(user_id: current_user.id)
  end

  # リアクションを編集するための画面
  def edit; end

  # 新しいリアクションを作成する
  def create
    @reaction = @answer.reactions.build(reaction_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @reaction.save
        format.html { redirect_to @answer.question, notice: t('reaction.create.success') }
        format.json { render :show, status: :created, location: @reaction }
      else
        flash[:error] = t('reaction.create.fail')
        format.html { render :new }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # リアクションを更新する
  def update
    respond_to do |format|
      if @reaction.update(reaction_params)
        format.html { redirect_to reaction_url(@reaction), notice: t('reaction.update.success') }
        format.json { render :show, status: :ok, location: @reaction }
      else
        flash[:error] = t('reaction.update.fail')
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # リアクションを削除する
  def destroy
    @reaction.destroy

    respond_to do |format|
      format.html { redirect_to @reaction.answer.question, notice: t('reaction.delete.success') }
      format.json { head :no_content }
    end
  end

  private

  # 共通のセットアップまたは制約を共有する
  def set_reaction
    @reaction = Reaction.find(params[:id])
  end

  # 回答を見つける
  def find_answer
    @answer = Answer.find(params[:answer_id])
  end

  # 信頼できるパラメータのリストのみを通す
  def reaction_params
    params.require(:reaction).permit(:answer_id, :body)
  end

  # 正しいユーザーか確認する
  def ensure_correct_user
    redirect_to(root_path) unless @reaction.user_id == current_user.id
  end
end

app/helpers/reactions_helper.rb
# frozen_string_literal: true

module ReactionsHelper
end

app/views/reactions/edit.html.erb
<div class="container">
  <div class="bg-light p-5 rounded my-4">
    <h2 class="col-12 ms-2">返信の編集</h2>
  </div>

  <%= form_with(model: @reaction) do |form| %>
    <% if @reaction.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@reaction.errors.count, "error") %> prohibited this reaction from being saved:</h2>
        <ul>
          <% @reaction.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="container p-5">
      <div class="field mb-3 w-100 row ml-0 mr-0">
        <%= form.text_area :body, class:"col-8 form-control" %>
      </div>

      <div class="actions">
        <%= form.submit '投稿', class: 'btn btn-success'  %>
      </div>
    </div>
  <% end %>
  <div class="my-4">
    <%= link_to '現在の質問に戻る', question_path(@reaction.answer.question), class: "link-success me-3" %>
    <%= link_to '質問投稿一覧', questions_path, class: "link-success me-3" %>
  </div>
</div>

app/views/reactions/index.html.erb
<h1>Reactions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Answer</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reactions.each do |reaction| %>
      <tr>
        <td><%= reaction.user_id %></td>
        <td><%= reaction.answer_id %></td>
        <td><%= reaction.body %></td>
        <td><%= link_to 'Show', reaction %></td>
        <td><%= link_to 'Edit', edit_reaction_path(reaction) %></td>
        <td><%= link_to 'Destroy', reaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reaction', new_reaction_path %>

app/views/reactions/new.html.erb
<div class="container">
  <div class="bg-light p-5 rounded my-4">
    <h2>返信する</h2>
  </div>

  <%= form_with(model: @reaction, url: answer_reactions_path(@reaction.answer.id), local: true) do |form| %>
    <% if @reaction.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@reaction.errors.count, "error") %> prohibited this reaction from being saved:</h2>

        <ul>
          <% @reaction.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.hidden_field :user_id, value: current_user.id %>

    <div class="field mb-3 w-100 row ml-0 mr-0">
      <%= form.label :body, '返信' %>
      <%= form.text_area :body %>
    </div>

    <div class="actions">
      <%= form.submit '投稿', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/reactions/show.html.erb
<div class="container p-5">
  <p>
    <strong>返信内容:</strong>
    <%= @reaction.body %>
  </p>

  <div class="my-4">
    <%= link_to '現在の質問に戻る', question_path(@reaction.answer.question), class: "link-success" %><br>
    <%= link_to '質問投稿一覧', questions_path, class: "link-success" %>
  </div>
</div>