config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'homes#top'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'account', to: 'dashboards#account'
  patch 'account', to: 'dashboards#update'

  get 'questions' => 'questions#index'
  get 'answers/search', to: 'answers#search'
  get 'answers' => 'answers#index'

  #タグ
  get 'tags/:tag_name', to: 'homes#tagged_questions', as: :tagged_questions

  # 退会確認画面
  get '/unsubscribe', to: 'dashboards#unsubscribe', as: 'unsubscribe'

  # 論理削除用のルーティング
  patch '/withdrawal', to: 'dashboards#withdrawal', as: 'withdrawal'

  resources :questions, shallow: true do
    resources :answers, shallow: true do
      resources :reactions
    end
  end

  resources :admin_articles, only: [:index, :show], path: 'articles'
end

app/models/answer.rb
# frozen_string_literal: true

# 各回答はユーザーと質問に関連づけられ、質問が削除された場合は依存関係により自動的に削除
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :reactions, dependent: :destroy

  validates :body, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[body created_at id question_id updated_at user_id]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[question reactions user]
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

# 質問に対する回答を管理するコントローラ
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: %i[search]
  before_action :set_answer, only: %i[show edit update destroy]
  before_action :ensure_correct_user, only: %i[edit update destroy]

  # 回答一覧を表示する
  def index
    @order = params[:order]
    @questions = load_questions(@order)
  end

  # 回答詳細を表示する
  def show; end

  # 新しい回答を作成するフォームを表示する
  def new
    load_question
    @answer = Answer.new(user_id: current_user.id, question_id: @question.id)
  end

  # 回答の編集フォームを表示する
  def edit; end

  # 回答を作成する
  def create
    load_question
    @answer = @question.answers.build(answer_params.merge(user_id: current_user.id))
    save_or_render_answer(:new, t('answer.create.success'), t('answer.create.fail'))
  end

  # 回答を更新する
  def update
    if @answer.update(answer_params)
      redirect_to @answer, notice: t('answer.update.success')
    else
      flash[:error] = t('answer.update.fail')
      render :edit, status: :unprocessable_entity
    end
  end

  # 回答を削除する
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: t('answer.delete.success') }
      format.json { head :no_content }
    end
  end

  # 検索機能
  def search
    if params[:keyword].blank?
      @questions = Question.all
      @cnt = Questions.all.count
    else
      @questions = Question.where('title LIKE?',
                                  "%#{params[:keyword]}%").or(Question.where('body LIKE?', "%#{params[:keyword]}%"))
      @cnt = @questions.count
    end
  end

  private

  # アクション間で共通のセットアップまたは制約を共有するためのコールバックを使用する
  def set_answer
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  # 信頼できるパラメータのリストのみを通す
  def answer_params
    params.require(:answer).permit(:question_id, :body)
  end

  # 質問を読み込む
  def load_question
    @question = Question.find(params[:question_id])
  end

  # 質問を順序付けて読み込む
  def load_questions(order)
    case order
    when 'recent'
      Question.order(created_at: :desc)
    when 'resolved'
      Question.where.not(best_answer_id: nil).order(updated_at: :desc)
    when 'popular'
      Question.order(views_count: :desc)
    else
      Question.all
    end
  end

  # 回答を保存またはレンダリングする
  def save_or_render_answer(fail_action, success_msg, fail_msg)
    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: success_msg }
        format.json { render :show, status: :created, location: @answer }
      else
        flash[:error] = fail_msg
        format.html { render fail_action, locals: { answer: @answer } }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # 回答を更新またはレンダリングする
  def update_or_render_answer(success_msg, fail_msg)
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to answer_url(@answer.question), notice: success_msg }
        format.json { render :show, status: :ok, location: @answer }
      else
        flash[:error] = fail_msg
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # 正しいユーザーか確認する
  def ensure_correct_user
    redirect_to(root_path) unless @answer.user_id == current_user.id
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/answers/edit.html.erb
<div class="container">
  <div class="bg-light p-5 rounded my-4">
    <h2 class="col-12 ms-2">回答の編集</h2>
  </div>

  <%= form_with(model: @answer) do |form| %>
    <% if @answer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
        <ul>
          <% @answer.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="container p-5">
      <div class="field mb-3 w-100 row ml-0 mr-0">
        <%= form.label :body %>
        <%= form.text_area :body, class:"col-8 form-control" %>
      </div>

      <div class="actions">
        <%= form.submit '投稿', class: 'btn btn-success'  %>
      </div>
    </div>
  <% end %>


  <div class="my-4">
    <%= link_to "現在の回答投稿に戻る", new_question_answer_path(@question), class: "link-success me-3" %>
    <%= link_to "回答募集一覧", answers_path, class: "link-success me-3" %>
  </div>
</div>

app/views/answers/index.html.erb
<div id="sort" class="container justify-content-center p-3">
  <div class="bg-light p-5 rounded my-4">
    <h2 class="col-12 ms-2">回答募集一覧</h2>
  </div>

  <div class="my-3">
    <h5>現在回答募集中の質問一覧です</h5>
  </div>

  <div class="d-flex justify-content-end mx-5">
    <%= link_to "新着順", { controller: "answers", action: "index", order: "recent" }, remote: true, class: "btn btn-light btn-outline-secondary btn-spacing" %>
    <%= link_to "閲覧数順", { controller: "answers", action: "index", order: "popular" }, remote: true, class: "btn btn-light btn-outline-secondary btn-spacing" %>
    <%= link_to "解決済み", { controller: "answers", action: "index", order: "resolved" }, remote: true, class: "btn btn-light btn-outline-secondary" %>
  </div>

  <div class="row text-center py-3 px-5">
    <% @questions.each do |question| %>
      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <div class="card-img-container">
            <% if question.image.attached? %>
              <%= image_tag question.image, class: "card-img-top" %>
            <% else %>
              <%= image_tag "question.png", class: "card-img-top" %>
            <% end %>
          </div>
          <div class="card-body">
            <h4 class="card-title question-title"><%= question.title %></h4>
            <p class="card-text  question-body"><%= question.body %></p>
          </div>
          <div class="card-footer">
            <%= link_to "回答する", new_question_answer_path(question.id), class: "link-success" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="my-4">
    <%= link_to "トップページ", root_path, class: "link-success me-3" %>
    <%= link_to "質問投稿一覧", questions_path, class: "link-success me-3" %>
  </div>
</div>

app/views/answers/index.js.erb
$('#sort .row.text-center').html('<% @questions.each do |question| %>\
  <div class="col-lg-3 col-md-6 mb-4">\
    <div class="card h-100">\
      <div class="card-img-container">\
        <% if question.image.attached? %>\
          <%= j image_tag(question.image, class: "card-img-top") %>\
        <% else %>\
          <%= j image_tag("question.png", class: "card-img-top") %>\
        <% end %>\
      </div>\
      <div class="card-body">\
        <h4 class="card-title question-title"><%= question.title %></h4>\
        <p class="card-text question-body"><%= question.body %></p>\
      </div>\
      <div class="card-footer">\
        <%= j link_to '回答する', new_question_answer_path(question.id), class: 'link-success' %>\
      </div>\
    </div>\
  </div>\
<% end %>');

app/views/answers/new.html.erb
<div class="container">
  <div class="bg-light p-5 rounded my-4">
    <h2 class="col-12 ms-2">回答投稿</h2>
  </div>

  <div class="my-3">
    <% if @question.user.image.attached? %>
      <%= image_tag @question.user.image, class: "rounded-circle", size: "60x60" %>
    <%else%>
      <%= image_tag "rabbit_logo.png", class: "rounded-circle", size: "60x60" %>
    <%end%>
    <span class="<%= "user_color" if current_user && current_user.id == @question.user_id %>">
      <%= @question.user.name %>
    </span>
  </div>

  <div>
    <div class="my-3">
      タイトル：<%= @question.title %><br>
      内容：<%= @question.body %><br>
    </div>
    <div class="my-3">
      <% @question.tags.each do |tag| %>
        <%= link_to tagged_questions_path(tag_name: tag.name), class: "btn btn-info" do %>
          <%= tag.name %>
        <% end %>
      <% end %>
    </div>
    <div>
      <% if @question.image.attached? %>
        <%= image_tag @question.image, class: "question-img my-5" %>
      <% end %>
    </div>

    <% if @question.best_answer_id.nil? %>
      <% unless current_user.id == @question.user_id %>
        <%= form_with(model: @answer, url: question_answers_path(@question), local: true) do |form| %>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
              <ul>
                <% @answer.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field mb-3 w-100 row ml-0 mr-0">
            <%= form.label :body, '回答' %>
            <%= form.text_area :body %>
          </div>

          <%= form.hidden_field :user_id, value: current_user.id %>

          <div class="actions">
            <%= form.submit '投稿', class: 'btn btn-success' %>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <h3 class="mt-5"><span class="p-2 border border-3 border-danger rounded-pill">解決済み</span></h3>
    <% end %>
  </div>

  <div class="row">
    <div class="p-5">
      <h3 class="col-12 ms-2">その他の回答</h3>
    </div>

    <div class="mb-5">
      <% @question.answers.each do |answer| %>
        <div class="col-lg-11 col-md-11">
          <div class="card h-100">
            <div class="card-body <%= "best-answer" if @question.best_answer_id == answer.id %>">
              <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                  <% if answer.user.image.attached? %>
                    <%= image_tag answer.user.image, class: "rounded-circle", size: "60x60" %>
                  <%else%>
                    <%= image_tag "rabbit_logo.png", class: "rounded-circle", size: "60x60" %>
                  <%end%>
                  <span class="<%= "user_color" if current_user && current_user.id == answer.user_id %>">
                    <%= answer.user.name %>
                  </span>
                </div>

                <% if current_user.id == answer.user_id %>
                  <div>
                    <% if answer && answer.persisted? %>
                      <%= link_to "編集", edit_answer_path(answer), class: "btn btn-light" %>
                    <% end %>

                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal-<%= answer.id %>">
                      削除
                    </button>
                  </div>

                  <!-- Modal -->
                  <div class="modal fade" id="deleteModal-<%= answer.id %>" tabindex="-1" aria-labelledby="deleteModalLabel-<%= answer.id %>" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="deleteModalLabel-<%= answer.id %>">削除の確認</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
                        </div>
                        <div class="modal-body">
                          この回答を削除してよろしいですか？
                        </div>
                        <div class="modal-footer">
                          <% if answer.persisted? %>
                            <%= link_to "削除", answer_path(answer), method: :delete, class: "btn btn-danger" %>
                          <% end %>
                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>

              <div class="my-3"><%= answer.body %></div>
              <% answer.reactions.each do |reaction| %>
                <div class="row">
                  <div class="col-lg-12 col-md-12">
                    <div class="card h-100">
                      <div class="card-body">
                        <div><%= reaction.body %></div>
                      </div>
                    </div>
                  </div>
                </div>
                <br>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="my-4">
    <%= link_to '前のページに戻る', request.referer || root_path, class: "link-success me-3" %>
    <%= link_to "トップページ", root_path, class: "link-success me-3" %>
    <%= link_to "回答募集一覧", answers_path, class: "link-success me-3" %>
  </div>
</div>

app/views/answers/search.html.erb
<div class="question container justify-content-center p-5">
  <div class="row">
    <% if @questions.any? %>
      <h3 class="col-12 search-number">検索結果 <%= @cnt %>件です</h3>
        <% @questions.each do |question| %>
          <div class="col-12">
            <div class="question-search-frame">
              <div class="card">
                <div class="question-search-profile card-header">
                <% if question.user&.image.present? %>
                  <%= image_tag url_for(question.user.image), class: "rounded-circle", size: "45x45" %>
                <% else %>
                  <%= image_tag "rabbit_logo.png", class: "rounded-circle", size: "45x45" %>
                <% end %>
                  <%= question.user.name %>
                </div>
                <div class="card-body">
                  <%= link_to new_question_answer_path(question), class:"question-link link-success" do %>
                    <div class="search-title card-title"><%= question.title %></div>
                  <% end %>
                  <div class="search-body card-text"><%= question.body %></div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
    <% else %>
      <div>
        <h3>検索結果はありませんでした</h3>
      </div>
    <% end %>
  </div>

  <div class="my-4">
    <%= link_to "トップページ", root_path, class: "link-success me-3" %>
  </div>
</div>

app/views/answers/show.html.erb
<div class="container p-3">
  <h5>回答投稿:</h5>
  <%= @answer.body %><br>

  <div class="my-4">
    <%= link_to "現在の回答投稿に戻る", new_question_answer_path(@question), class: "link-success me-3" %>
    <%= link_to "回答募集一覧", answers_path, class: "link-success me-3" %>
  </div>
</div>